name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-lint-typecheck-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
